### ISSUE TITLE
[4.0] Adonis CLI Installer

### ISSUE THREAD

**Issue by RomainLanz** [adonisjs/discussion#12]
Dear everyone!

We have some though on re-writing the `adonis-cli` package. This package was used to add the command `adonis` in your path that let you create a new AdonisJs application.

Currently it got these features:

* Checking the version of Node.js & npm
* Cloning the repository in the given folder
* Installing dependencies via `npm`

<hr> 

**Here is my proposition for the rework of `adonis-cli`.**

First of all, I would ask to change its name to `adonis-installer`, because it is what it does and that may be simpler for any newcomers.

Secondly, I propose to switch the current implementation by using `yeoman` instead of writing something from scratch. `yeoman` is used a lot by developper and let us easily create a generator for Adonis. We can also write another version of the CLI by using `adonis-ace` which was the proposition of @thetutlage. Using `adonis-ace` could be interesting to show an example of an external CLI tool build with this package.

Thirdly, the CLI need to check if `yarn` is installed and available in the system and then ask the developer if which one he wanna use.

The output of the CLI should be also more consistent and easy to understand for newcomers and to provide a robust "opinion" of the framework.

Maybe a little "geeky", but it could be cool if we add an ASCII art at the beginning of the input and some emoji like `yarn` or `brew` do. The ASCII art could be something like the one bellow.

```
    ___       __            _          __    
   /   | ____/ /___  ____  (_)____    / /____
  / /| |/ __  / __ \/ __ \/ / ___/_  / / ___/
 / ___ / /_/ / /_/ / / / / (__  ) /_/ (__  ) 
/_/  |_\__,_/\____/_/ /_/_/____/\____/____/  
                                             
```

I'm also thinking that it could be great to download a zip and then unzip it instead of cloning the repository. This may remove the dependency around `git`.

**Comment by rtablada** [comment]
Having worked with Yeoman, it can work but could be a bit awkward to make a whitelisted tool wrapping around it.

Let me ask to see if the Ember CLI team has any recommendations around how they tackled the project blueprint.
What is interesting around what they have is that you can have your local blueprint or specify a blueprint via Git remote or IIRC NPM package.

So for instance to get the newest `master` of Adonis you could run:

```
adonis new --blueprint=https://github.com/adonis/adonis-app.git" todo-app
```

**Comment by rtablada** [comment]
This could actually be shortened to something like `adonis new todo-app --master`

**Comment by atinux** [comment]
It could be great if the CLI is made with `adonis-ace`, it will show how powerful AdonisJS is!

**Comment by RomainLanz** [comment]
> It could be great if the CLI is made with adonis-ace, it will show how powerful AdonisJS is!

I have already started building that but I'm waiting for the approval to continue it. I still think that it is one of the best solution.

Lets wait for @thetutlage to tell us what he thinks about that.

**Comment by thetutlage** [comment]
@RomainLanz I agree currently, `adonis-cli` currently works like an installer only. My plans with `adonis-cli` are little different.

I want it to be the only command line tool for AdonisJs going forward. So it will proxy all the commands from `ace` and will it's own commands. Here is the list of responsibilities.

1. Move all generator commands like `make:<>` to adonis-cli, since these commands do not require any project specific modules/config.

2. Proxy all commands from ace, meaning one can run `adonis migration:run`, instead of `ace migration:run`.

3. Test runner will be embedded into `adonis-cli`, so that you can run tests saying. `adonis test`

**Comment by RomainLanz** [comment]
I completely agree with that!

The version that I have wrote works well with the `new` command atm (it uses `yarn` and fallback to `npm`).
I'll update it to follow your changes.

<img width="635" alt="screen-shot-2017-01-07-at-00 45 08" src="https://cloud.githubusercontent.com/assets/2793951/21749242/6aebf35c-d59b-11e6-90fc-873e5bf2b74a.png">

**Comment by atinux** [comment]
Looks really nice! Great job!

Is it keeping the .git history when cloning or it's a fresh start?

Will it be possible to clone from another repository? Like `adonis new nuxt/adonuxt my-project`?

**Comment by RomainLanz** [comment]
It removes the `.git` folder (`clean` step) so it's a complete fresh install of AdonisJs.

That's a good idea to let the developper choose if he wants to start with another blueprint.

I could add what @rtablada said in the API:

```bash
$ adonis new myProject --blueprint=adonis/adonis-app
```

**Comment by thetutlage** [comment]
Yup i'll be sharing a list of tasks to be taken care of in `adonis-cli` by tonight

**Comment by thetutlage** [comment]
`adonis-cli` has been a very thin tool to scaffold new AdonisJs apps from command line. For the newer release we have some big plans.

@RomainLanz expressed interest in owning the module to be used by everyone in the future.

To make sure that anyone in the community can contribute to this module in future, @RomainLanz make sure you adhere to guidelines described in [AdonisJs contribution guidelines](https://github.com/adonisjs/discussion/issues/18)

## Todo
- [ ] Make sure all commands are ran within the project root, apart from `adonis new`. Same can be checked with the existence of ace file.
- [ ] Build a base command that other commands can extend for common functionality, like *output style* etc
- [ ] Command executed should be looked first first into `adonis cli`, if not found, it should spawn a new process to run `node ace` and pass all arguments to the ace command.
- [ ] All blueprints generator will be moved to the cli core.
- [ ] Installation process should do a series of actions. 
	* First check for installed node+npm versions and make sure they satisfy the Adonis requirements semver.
	* Clone the given template from git into a `tmp` folder.
	* Prompt for modules installer, *yarn* or *npm* (Adonisjs does not guarantee yarn support).
	* If a template has `prompts.js` file, simply loop over those prompts. This will help the template author to make configurable repos.
	* All prompt answers will be passed to the template files to be parsed as mustache templates.
	* Finally install dependencies.
- [ ] Have a solid test suite of individual classes and functional tests.
- [ ] Have proper docblocks for API docs.
- [ ] Keep the output pretty.
- [ ] Do not use `synchronous` commands like `fsSync`. Instead use `fs-extra` and `pify`.

## Commands to be supported

#### new `{path} {—skip-install} {—dev} {—template}`
—skip-install: To skip the installation process from npm or yarn.
—dev: Get the template from the `develop` repo.
—template: Template to be used, if not defined it will be `adonis-app`.

#### make:<entity> `{path}`
Simply port all make commands to cli core.

#### install: `{addon} {—noop}`
Install an addon from npm using *npm* or *yarn*. It will perform following operations.
	* Install from npm.
	* Run `instructions.js`
Do not run `instructions.js`	 when *—noop* flag is passed.

**Comment by RomainLanz** [comment]
Closing since https://github.com/adonisjs/adonis-cli has been released.
