### ISSUE TITLE
Testing With AdonisJs

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/discussion#22]
Testing is a very broad concept combined with several small pieces to offer a nice testing experience. With AdonisJs the concept is even trivial, since AdonisJs offers a lot more then any other framework in the Node eco-system.

## Isolated Modules

- [x] Embeddable test runner to write and run tests. It has nothing to do how tests are written and only focuses on the running the tests and outputs formatted results.  https://github.com/thetutlage/japa
- [x] Driver to test webpages with Javascript interaction. It requires Selenium for the webpages to be tested in real Javascript environment. http://webdriver.io/
- [x] Testing Non-Javascript webpages inside a headless browser. http://zombie.js.org/
- [ ] Testing JSON api endpoints is simple and clean way possible.

## Testing Experience

Testing applications with different nature is tricky, since test runner needs to know when to boot HTTP server and when to make the requests via Selenium. In order to all this automated, without the user worrying about defining the testing mode, we need to divide the testing into multiple types.

### Unit Tests
Unit tests are written to test the individual pieces of code in isolation. They do not require the HTTP interface to execute the test. If you ever feel like testing **a route** or **a controller**. It means you need a `functional test` over a unit test.

### Functional Tests
Functional tests are outside in tests, where you interact with the application like a User. Means hitting a route and then asserting on the response to make sure all is good. AdonisJs will offer lot of tooling for **Faking Logins**, **Mocking Mailer** to make sure the testing experience is smooth.

Functional tests will boot the HTTP server but cannot test Javascript code on the webpages.

#### End to End Tests
End to end tests are required your webpages relies on Javascript, for example: **making Ajax calls**, **toggle some modal box** etc. For these tests, AdonisJs will fire a Selenium server and execute tests inside a real web browser, like a user will do.

## Todo
Todo is yet to be updated, since their is lot of other important work pending for the release of 4.0

**Comment by lmj0011** [comment]
good stuff. looking forward to the e2e implementation

**Comment by lmj0011** [comment]
@thetutlage 

Currently, what's the suggested way to get started with Unit Testing in Adonisjs?

**Comment by webdevian** [comment]
@lmj0011 There's a nice starter test framework in the adonisjs/adonis-rally project.

Only thing it's missing is E2E tests. I'm just trying to work out the best to fire up the webdriverio browser object within this file structure. Any ideas @thetutlage?

**Comment by nrempel** [comment]
Thanks for writing this @thetutlage!

I have a question about unit tests and controllers.

Would it not be fairly simple to provide mock AdonisJS request/response objects to be passed into server controller methods? These objects could have a nice interface to add params or to add inputs  so that you can call your controller methods in unit tests easily.

In this case, controllers could be unit tested instead of requiring functional tests.

Is there something wrong with this approach?

**Comment by thetutlage** [comment]
Ideally you should test your controller like an outside by writing functional tests. Which means, hit a route like a normal user would do.

If you have specific pieces of code containing domain logic, you should abstract them into plain Services and unit test them.

**Comment by thetutlage** [comment]
Testing is ready and will be shipped in final release of 4.0, which is not much far away

**Comment by aliharis** [comment]
Is there a way to isolate the testing environment data? I couldn't figure out a way to run the migrations on a separate database for testing. Frameworks unlike Laravel & Rails, the feature comes right out of the box.

How do we go about this?
